package com.ashy0019.hapticscape.remote;

enum RemoteMessageType
{
	HELLO,
	SETTINGS_SEED,
	SETTINGS_SEED_ACK,
	SETTINGS,
	SETTINGS_ACK,
	SETTINGS_REJECTED,
	PERMISSIONS,
	REMOTE_ACTION,
	REMOTE_ACTION_ACK,
	LOCK_PROPOSAL,
	LOCK_ACCEPTED,
	LOCK_DECLINED,
	LOCK_CANCEL_REQUEST,
	LOCK_CANCELLED,
	EMERGENCY_PAUSED,
	SESSION_RESUMED,
	SESSION_END
}
